version: '3.8'
services:
  nginx1:
    container_name: nginx1
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    depends_on:
      - nginx2
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data1:/usr/share/nginx/csv
    networks:
      - app_network

  nginx2:
    container_name: nginx2
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    ports:
      - "8082:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data:/usr/share/nginx/csv
    networks:
      - app_network

  nginx3:
    container_name: nginx3
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    ports:
      - "8083:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data:/usr/share/nginx/csv
    networks:
      - app_network

  nginx4:
    container_name: nginx4
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    ports:
      - "8084:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data:/usr/share/nginx/csv
    networks:
      - app_network

  nginx5:
    container_name: nginx5
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    ports:
      - "8085:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data:/usr/share/nginx/csv
    networks:
      - app_network

  nginx6:
    container_name: nginx6
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    ports:
      - "8086:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data:/usr/share/nginx/csv
    networks:
      - app_network

  nginx7:
    container_name: nginx7
    annotations:
      - customization.image.slug=nginx
    labels:
      - traefik.http.routers.my-container.rule=Host(`test.minilab.cloud`)
    image: nginx:1.28.2-alpine
    ports:
      - "8087:80"
    restart: unless-stopped
    environment:
      - TEST_VAR=${TEST_VAR}
      - TEST_VAR1=${TEST_VAR1}
      - TEST_VAR2=${TEST_VAR2}
      - TEST_VAR3=${TEST_VAR3}
      - TEST_VAR4=${TEST_VAR4}
    command: >
      sh -c "echo '<html><body><h1>Env Vars</h1><pre>' > /usr/share/nginx/html/index.html
      && env | sort >> /usr/share/nginx/html/index.html
      && echo '</pre></body></html>' >> /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
    volumes:
      - nginx_data:/usr/share/nginx/csv
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx_data:
    driver: local

  nginx_data1:
    driver: local

